using Test
using Random
using Ark
using PWNModel

include("comps/tree.jl")
include("comps/cell.jl")
include("res/grid.jl")
include("res/rng.jl")
include("util/shuffle.jl")
include("ecs/res/tick.jl")
include("ecs/res/termination.jl")
include("ecs/config.jl")
include("ecs/sys/fixed_termination.jl")
include("scheduler.jl")
include("ecs/stats.jl")
include("observers.jl")
include("reporter/csv_reporter.jl")
include("sys/init_grids.jl")
include("sys/init_trees.jl")
include("sys/update_time.jl")
include("sys/disease_course.jl")
include("sys/random_release.jl")
include("sys/damage_trees.jl")
include("sys/beetle_emergence.jl")
include("sys/beetle_mortality.jl")
include("sys/colonization.jl")
include("sys/tree_attraction.jl")
include("obs/maps/tree_colonization.jl")
include("obs/maps/beetles.jl")
